#!/bin/python

import json
import time

with open('/home/hamtarowarrior/Documents/dofus/almanax.json') as data_file:
    data = json.load(data_file)

day_data = data["dofus"][time.strftime("%m-%d")]

print("L'offrande du jour est : ", day_data["offering"], "\nLe bonus du jour est : ", day_data["bonusDescription"])
