#!/bin/bash

TORRENT_HOME=$HOME/Downloads/torrents/
DONE_TORRENT_HOME=$HOME/Downloads/donetorrents/
PENDING_FILE=$TORRENT_HOME/pending
DL_HOME=$HOME/Videos/
SEEDBOX=funkysayu@seedbox.funkysayu.fr
SEEDBOX_HOME=/media/sdi1/home/funkysayu/
SEEDBOX_RAPH_TORRENT_PATH=$SEEDBOX_HOME/private/rtorrent/watch/Raph
SEEDBOX_RAPH_FINISHED_PATH=$SEEDBOX_HOME/private/rtorrent/finished/Raph
SEEDBOX_SEED_TORRENT_PATH=$SEEDBOX_HOME/private/rtorrent/watch/SeedRaph
SEEDBOX_SEED_FINISHED_PATH=$SEEDBOX_HOME/private/rtorrent/finished/SeedRaph

NONE="\033[00m"
GREEN="\033[01;32m"

function main {
    while [ 1 = 1 ]; do
        clear
        echo -e ${GREEN}'Gestionnaire de torrents sur seedbox!'
        echo -e 'Que voulez vous faire?' ${NONE}
        echo '(1) Ajouter un nouveau torrent'
        echo '(2) Voir les torrents en attente de telechargement local'
        echo '(0) Quitter'
        read opt

        case $opt in
            1) 
                ls $TORRENT_HOME | grep .torrent > /dev/null && menuaddtorrent || echo "There is no torrent here."
                ;;
            2)
                menudl
                ;;
            0)
                exit 0
                ;;
        esac
    done
}

function menuaddtorrent {
    echo -e ${GREEN}"\nChoisissez votre dossier"${NONE}"\n"
    ARRAY="$(find $TORRENT_HOME -name "*.torrent")"
    select file in "${ARRAY}" "Retour"; do
        if [ "$file" = "Retour" ]; then
            return
        fi
        echo -e ${GREEN}"\nAjouter en tant que"${NONE}"\n"
        select USER in "Raph" "Seed" "Retour"; do
            if [ $USER = "Retour" ]; then
                return
            else
                addtorrent $USER "$file"
            fi
            break
        done
        break
    done
}

function addtorrent {
    USER=$1
    file=$2
    if [ $USER = "Raph" ]; then
        SEEDBOX_TORRENT_PATH=$SEEDBOX_RAPH_TORRENT_PATH
    else
        SEEDBOX_TORRENT_PATH=$SEEDBOX_SEED_TORRENT_PATH
    fi
    scp "$file" $SEEDBOX":"$SEEDBOX_TORRENT_PATH"/."
    if [ $USER = "Raph" ]; then
        TORRENT_NAME="$(torrent-reader "$file" | grep ".info.name" | awk '{ $1=""; print substr($0,2) }')"
        if [ -z "${TORRENT_NAME}" ]; then
            TORRENT_NAME="${file%.*}"
        fi
        echo $TORRENT_NAME >> $PENDING_FILE
    fi
    mv "$file" $DONE_TORRENT_HOME/.

}

function menudl {
    echo -e ${GREEN}"\nOu voulez vous telecharger?\n"${NONE}
    options=("Pending" "Dossier" "Retour")
    select opt in "${options[@]}"; do
        case $opt in
            Pending)
                menudlpending
                ;; 
            Dossier)
                menudlall
                ;;
            Retour)
                return
                ;;
        esac
        break
    done
}

function menudlpending {
    readarray ARRAY < $PENDING_FILE
    select opt in "${ARRAY[@]}" "Retour"; do
        if [ -z "$opt" ]; then
            echo "Fichier inexistant"
        else
            if [ "$opt" = "Retour" ]; then
                return
            fi
            opt=$(echo $opt | sed 's/\[/\\\[/g')
            opt=$(echo $opt | sed 's/\]/\\\]/g')
            NAME=$(ssh $SEEDBOX ls $SEEDBOX_RAPH_FINISHED_PATH | grep "$opt*" | sed 's/ /\\\ /g')
            if [ ! -z "$NAME" ]; then
                opt=$(sed 's/\./\\\./g' <<< $opt)
                NAME=$(sed 's/\[/\\\[/g' <<< $NAME)
                NAME=$(sed 's/\]/\\\]/g' <<< $NAME)
                NAME=$(sed 's/(/\\\(/g' <<< $NAME)
                NAME=$(sed 's/)/\\\)/g' <<< $NAME)
                scp -r $SEEDBOX:$SEEDBOX_RAPH_FINISHED_PATH/"${NAME}" $DL_HOME/. && sed -i "/$opt/d" $PENDING_FILE            
            else
                echo "Le dossier n'est pas la"
            fi
            break
        fi
    done
}

function menudlall {
    readarray FILES < <(ssh $SEEDBOX ls $SEEDBOX_RAPH_FINISHED_PATH)
    select opt in "${FILES[@]}" "Retour"; do
        if [ -z "$opt" ]; then
            echo "Fichier inexistant"
        else
            if [ $opt = "Retour" ]; then
                echo toto
                return
            fi
            NAME=$(sed 's/ /\\\ /g' <<< $opt)
            scp -r "$SEEDBOX:$SEEDBOX_RAPH_FINISHED_PATH/$NAME" $DL_HOME/.
            break
        fi
    done
}

main
