#!/bin/sh

# Execute a command in a screen.
# The screen will be named after the first argument (often the command)
# If the screen already exists, it will use an existing one

COMMAND=$@
MAIN=$1

# Uncomment the following line and delete the next one if you want
# to delete the screen if it exists before creating a new one
# screen -ls | grep "$MAIN" && screen -X -S "$MAIN" quit; screen -dmS $MAIN sh
screen -ls | grep "$MAIN" || screen -dmS $MAIN sh
screen -S $MAIN -X stuff "$COMMAND
"
