#!/bin/bash

# The purpose of this script is to manage multi account playing (on Dofus).
# For every window named on the `NAMES` array, if a click is perfomed on a
# window, it is done on every window

# This script is intended to be used with i3 (or any system that allows you
# to handle yourself your mouse buttons

# For more, see my i3 config at
# https://github.com/raphaelehret/config/blob/master/i3/config

ACTION=$1
NUMBER=$2

CURRENT="$(xdotool getactivewindow)"
CURRENT_NAME="$(xdotool getactivewindow getwindowname)"
NAMES=("Saphirell" "Bakkabakka" "Negeko" "Ikaros-Alpha")

isInArray=0

for e in "${NAMES[@]}"; do
    [[ "$e"="$NAMES" ]] && isInArray=1
done

if [[ "$isInArray" -eq 0 ]]; then
    xdotool click 1;
    exit;
fi
#[[ "$isInArray" -eq 0 ]] && xdotool click 1 && exit;

PID="$(xdotool search --name "$CURRENT_NAME")"
xdotool click --window $PID $NUMBER
sleep 0.1

for NAME in "${NAMES[@]}"; do
    if [ "$NAME"!="$CURRENT_NAME" ]; then
        PID="$(xdotool search --name "$NAME")"
        if [ ! -z $PID ]; then
            xdotool windowactivate $PID
            xdotool click --window $PID $NUMBER
            sleep 0.1
        fi
    fi
done

xdotool windowactivate $CURRENT
