#!/bin/bash

# The purpose of this script is to manage multi account playing (on Dofus).
# For every window named on the `NAMES` array, if a click is perfomed on a
# window, it is done on every window

# This script is intended to be used with i3 (or any system that allows you
# to handle yourself your mouse buttons

# For more, see my i3 config at
# https://github.com/raphaelehret/config/blob/master/i3/config

ACTION=$1
NUMBER=$2

CURRENT="$(xdotool getactivewindow)"
NAMES=("Saphirell" "Bakkabakka" "Dofus")

for NAME in "${NAMES[@]}"; do
    PID="$(xdotool search --NAME "$name")"
    echo $PID
    if [ ! -z $PID ]; then
        xdotool windowactivate $PID
        xdotool "$ACTION" --window "$PID" "$NUMBER"
    fi
done

xdotool windowactivate $CURRENT
