#!/bin/bash

ACTION=$1
NUMBER=$2

CURRENT="$(xdotool getactivewindow)"
NAMES=("Saphirell" "Bakkabakka" "Dofus")

for NAME in "${NAMES[@]}"; do
    PID="$(xdotool search --NAME "$name")"
    echo $PID
    if [ ! -z $PID ]; then
        xdotool windowactivate $PID
        xdotool "$ACTION" --window "$PID" "$NUMBER"
    fi
done

xdotool windowactivate $CURRENT
