#!/usr/bin/env python3

### Author : Raphael EHRET
### Name : rsearch
### Mail : ehretrapha[at]eisti[dot]eu
### Langage : python 3
### Type : script
### 
### Description : open reverse engines in a browser to reverse search a given link
###                 or file. By default, the browser is your default browser. The
###                 url of the engines are specified in a file on the path
###                 stocked in `urlfile`.
###                 If it is invalid, google reverse search will be open by default
###                 
### 
### Required :
### 
### Arguments :
###     [-f filename]: read urls in a file rather than an url


import webbrowser
import os
import sys

### MODIFY ME
# Url of the file containing the urls of the engines
urlfile='~/.config/rsearch/urls'
# Separator used on the url file
sep=' '
# Browser used by the script
browser='firefox'

argsin = sys.argv
URLS = {}
try:
    f = open(os.path.expanduser(urlfile))
except:
    print("Didn't find url file at the indicated location, using google reverse search by default")
    URLS['google']='https://www.google.com/searchbyimage?&image_url='
else:
    for l in f.readlines(): 
        l = l.rstrip()
        if l:
            if l[0] != '#':
                try:
                    name,url = l.split(sep)
                except Exception as e:
                    print(str(e))
                    print('Error : error while reading the URL files, exited with code 1')
                    exit(1)
                URLS[name]=url

if len(argsin) < 2:
    print('Error : No URL specified, exited with code 1')
    exit(1)
elif argsin[1] == '-f':
    if len(argsin) == 2:
        print('Error : No file specified, exited with code 1')
        exit(1)
    f = open(argsin[2])
    imageurls = [s.strip() for s in f.readlines() if s.strip()]
    f.close()
else:
    imageurls = argsin[1:]
try:
    wb = webbrowser.get(browser)
except:
    print('Warning : the given browser is invalid, opening with default browser')
    wb = webbrowser.get()

for imageurl in imageurls:
    print('\nOpening image : '+imageurl)
    for name,url in URLS.items():
        print('Opening the '+name+' reverse search')
        wb.open_new_tab(url+imageurl)
print('Done')
