#!/bin/bash -e

##############################################################################
###                                                                        ###
###  File : toggle_layout                                                  ###
###  Language : bash                                                       ###
###  Description :  Toggle change on keyboard layout to switch             ### 
###     between fr and us                                                  ###
###                                                                        ###
###  Dependencies : setxkbmap                                              ###
###                                                                        ###
###  Author : Raphael Ehret                                                ###
###  E-mail : raphael.ehret@gmail.com                                      ###
###                                                                        ###
##############################################################################
#
# Status file for the layout of the keyboard
STATUS_DIR="/tmp/layout"

main() {
    local map
    local layout

    map=$(setxkbmap -query | grep -i 'layout' | awk '{ print $2 }')
    [ "X$map" = "Xus" ] && layout="fr" || layout="us"
    setxkbmap "$layout" 
    mkdir -p "${STATUS_DIR}" && rm "${STATUS_DIR}/"*
    touch "${STATUS_DIR}/${layout}"
}

main
