#!/usr/bin/env python3

try:
    from gmusicapi import Musicmanager
    from gmusicapi import Mobileclient
except ImportError:
    sys.exit("Please download the gmusicapi with the command : `pip install --user gmusicapi`")

import oauth2client.client
import sys
import os
import glob

def print_usage():
    print(''' Usage :
        upload-playlists folder
    ''')
    exit(1)

FILETYPE="mp3"

class UploadManager():
    def __init__(self, folder):
        self.mm = Musicmanager()
        self.mc = Mobileclient()
        self.root_folder = folder

        self.mmlogin()

    def mmlogin(self):
        if not self.mm.login():
            try:
                self.credentials = self.mm.perform_oauth()
            except oauth2client.client.FlowExchangeError:
                sys.exit("Error while performing the oauth identification")
            if not self.mm.login(self.credentials):
                sys.exit("Could not login")
            else:
                print("Logged in!")
        else:
            print("Logged in!")

    #def mclogin():
        #read credentials from a  file
        #check if login successful

    def upload_playlists(self):
        folder_list = [ f[0] for f in os.walk(self.root_folder) ]
        for f in folder_list:
            music_list = glob.glob(f + "/*." + FILETYPE)
            folder_name = f.split('/')[-1]
            uploaded_songs_id = self.mm.upload(music_list)

            #playlists_list = self.mc.get_all_playlists()

            #for playlist in playlists_list:
            #    if playlist['name'] == folder_name:
            #        self.playlist_id = playlist['id']
            #else:
            #    self.playlist_id = self.mc.create_playlist(folder_name)

            #self.mc.add_songs_to_playlist(playlist_id, uploaded_songs_id)


    
if __name__ == '__main__':
    if len(sys.argv) != 2:
        print_usage()
    um = UploadManager(sys.argv[1])
    um.upload_playlists()

